---
title: "Flowering Models Fitted"
author: "Loïc Pages"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  word_document: default
  html_document:
    df_print: paged
---

# Introduction

```{r}
rm(list=ls())
library(knitr)
library(spaMM)
library(tidyverse)
library(splines)
library(patchwork)
library(SplinesUtils)

setwd("/media/loic/Commun/0Travail/Stage 2025 ISEM/Models")

centauree_data <- read.csv("donnesIPM_short.csv")
centauree_data_complet <- read.csv("donnesIPM.csv")


#Supprimer plantes dont l'age est inconnu
centauree_data <- centauree_data[!is.na(centauree_data$age0), ]
centauree_data$age1 <- ifelse(centauree_data$Stage1=="V",centauree_data$age0+1,NA)

#Forcer l'age maximal à 8
length(centauree_data$age0[centauree_data$age0 >= 8])
centauree_data$age0[centauree_data$age0 > 8] <- 8

spaMM.options(separation_max=70)
```


```{r}
annees <- 1995:2022
populations <- c("Po","Au","Pe","E1","E2","Cr")
taille_range <- seq(0.5, 25, by = 0.5) 
age_range <- 1:8

fake_data <- expand.grid(
  year = annees,
  Pop = populations,
  Size0Mars = taille_range,
  age0 = age_range
)

fake_data <- fake_data %>% 
  mutate(Nrw = row_number())
```

BIC
```{r}
# N the number of subjects
# ntot the total number of observations
extractBIC <- function(fit, ntot, N){
  extractAIC(fit)[[2]] +(log(ntot)-2)*DoF(fit)[[3]] + log(N)*DoF(fit)[[1]]
}
```

# Flowering probability

```{r}
centauree_data %>%
  group_by(Size0Mars) %>%
  mutate(floweringProba = sum(Flowering0, na.rm = TRUE) / n()) %>% 
  ggplot(aes(x = Size0Mars, y = Flowering0)) +
  geom_count(alpha = 0.6) +  
  geom_point(aes(y = floweringProba), color = "red", size = 0.5) +
  labs(title = "Relation entre la taille et la floraison",
    x = "Taille",
    y = "Floraison") +
  ylim(0, 1) +
  theme_minimal()

centauree_data %>%
  group_by(age0) %>%
  mutate(floweringProba = sum(Flowering0, na.rm = TRUE) / n()) %>% 
  ggplot(aes(x = age0, y = Flowering0)) +
  geom_count(alpha = 0.6) +  
  geom_point(aes(y = floweringProba), color = "red", size = 0.5) +
  geom_line(aes(y = floweringProba), color = "red") +
  labs(title = "Relation entre la taille et la floraison",
    x = "age",
    y = "Floraison") +
  ylim(0, 1) +
  theme_minimal()

```


AIC
```{r}
Flowglm1 <- fitme(Flowering0 ~  1 + poly(Size0Mars,3) + poly(age0,2) + (age0|Pop),
                 family=binomial,
                 data=centauree_data, method="PQL/L")

Flowglm2 <- fitme(Flowering0 ~  1 + poly(Size0Mars,3) + poly(age0,4) + (age0|Pop),
                 family=binomial,
                 data=centauree_data, method="PQL/L")

Flowglm3 <- fitme(Flowering0 ~  1 + poly(Size0Mars,4) + poly(age0,2) + (age0|Pop),
                 family=binomial,
                 data=centauree_data, method="PQL/L")

Flowglm4 <- fitme(Flowering0 ~  1 + poly(Size0Mars,3) + poly(age0,2) + (age0|Pop) + (1|year),
                 family=binomial,
                 data=centauree_data, method="PQL/L")

Flowglm5 <- fitme(Flowering0 ~  1 + poly(Size0Mars,3) + poly(age0,3) + (age0|Pop),
                 family=binomial,
                 data=centauree_data, method="PQL/L")
```



new BIC

```{r}
Flowglm1 <- fitme(Flowering0 ~  1 + poly(Size0Mars,3) + poly(age0,2),
                 family=binomial,
                 data=centauree_data, method="PQL/L")

Flowglm2 <- fitme(Flowering0 ~  1 + poly(Size0Mars,3) + poly(age0,2) + (1|Pop),
                 family=binomial,
                 data=centauree_data, method="PQL/L")

Flowglm3 <- fitme(Flowering0 ~  1 + poly(Size0Mars,4) + poly(age0,2),
                 family=binomial,
                 data=centauree_data, method="PQL/L")

Flowglm4 <- fitme(Flowering0 ~  1 + poly(Size0Mars,3) + poly(age0,3),
                 family=binomial,
                 data=centauree_data, method="PQL/L")

Flowglm5 <- fitme(Flowering0 ~  1 + poly(Size0Mars,3) + poly(age0,2) + (1|year),
                 family=binomial,
                 data=centauree_data, method="PQL/L")
```

```{r}
ntot <- length(centauree_data$Nrw)
N <- length(unique(centauree_data$Nrw))
extractAIC(Flowglm1) ; extractBIC(Flowglm1, ntot,N)
extractAIC(Flowglm2) ; extractBIC(Flowglm2, ntot,N)
extractAIC(Flowglm3) ; extractBIC(Flowglm3, ntot,N)
extractAIC(Flowglm4) ; extractBIC(Flowglm4, ntot,N)
extractAIC(Flowglm5) ; extractBIC(Flowglm5, ntot,N)

```

```{r}
summary(Flowglm1)
summary(Flowglm2)
summary(Flowglm3)
summary(Flowglm4)
summary(Flowglm5)
```

```{r,results='hide'}
Flowpredict1 <- predict(Flowglm1, newdata = fake_data)[,1]
Flowpredict2 <- predict(Flowglm2, newdata = fake_data)[,1]
Flowpredict3 <- predict(Flowglm3, newdata = fake_data)[,1]
Flowpredict4 <- predict(Flowglm4, newdata = fake_data)[,1]
Flowpredict5 <- predict(Flowglm5, newdata = fake_data)[,1]
```


```{r}
plot_flow <- function(data = fake_data, prediction, var, c1, valc1 = 1, c2, valc2 = "Au", fact, mindat, maxdat) {
  data %>%
    mutate(flow_predi = prediction) %>%
    filter(!!sym(c1) == valc1, !!sym(c2) == valc2) %>%
    ggplot(aes(x = .data[[var]], y = flow_predi)) +
    geom_vline(xintercept=maxdat, lty="dotted")+
    geom_vline(xintercept=mindat, lty="dotted")+
    geom_line(aes(color = as.factor(.data[[fact]]))) +
    theme_minimal() +
    ylim(0, 1)
}
```

## Floraison en fonction de la taille

### En fixant la population : voir l'effet année
```{r}
var <- "Size0Mars"
c1 <- "age0"
c2 <- "Pop"
valc2 <- "Au"
fact <- "year"
```

```{r,warning=FALSE,echo=FALSE,fig.show='hide'}
valc1 <- 1
maxdat <- max(centauree_data$Size0Mars[centauree_data$age0==valc1])
mindat <- min(centauree_data$Size0Mars[centauree_data$age0==valc1])

wrap_plots(
plot_flow(prediction = Flowpredict1, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict2, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict3, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict4, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict5, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat)
)

valc1 <- 3
maxdat <- max(centauree_data$Size0Mars[centauree_data$age0==valc1])
mindat <- min(centauree_data$Size0Mars[centauree_data$age0==valc1])
wrap_plots(
plot_flow(prediction = Flowpredict1, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict2, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict3, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict4, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict5, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat)
)

valc1 <- 8
maxdat <- max(centauree_data$Size0Mars[centauree_data$age0==valc1])
mindat <- min(centauree_data$Size0Mars[centauree_data$age0==valc1])
wrap_plots(
plot_flow(prediction = Flowpredict1, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict2, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict3, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict4, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict5, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat)
)
```

### En fixant l'année : voir l'effet population
```{r}
var <- "Size0Mars"
c1 <- "age0"
c2 <- "year"
valc2 <- 2000
fact <- "Pop"
```

```{r,warning=FALSE,echo=FALSE,fig.show='hide'}
valc1 <- 1
maxdat <- max(centauree_data$Size0Mars[centauree_data$age0==valc1])
mindat <- min(centauree_data$Size0Mars[centauree_data$age0==valc1])
wrap_plots(
plot_flow(prediction = Flowpredict1, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict2, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict3, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict4, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict5, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat)
)

valc1 <- 3
maxdat <- max(centauree_data$Size0Mars[centauree_data$age0==valc1])
mindat <- min(centauree_data$Size0Mars[centauree_data$age0==valc1])
wrap_plots(
plot_flow(prediction = Flowpredict1, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict2, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict3, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict4, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict5, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat)
)

valc1 <- 8
maxdat <- max(centauree_data$Size0Mars[centauree_data$age0==valc1])
mindat <- min(centauree_data$Size0Mars[centauree_data$age0==valc1])
wrap_plots(
plot_flow(prediction = Flowpredict1, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict2, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict3, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict4, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict5, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat)
)
```

## Floraison en fonction de l'age

### En fixant la population : voir l'effet année
```{r}
var <- "age0"
c1 <- "Size0Mars"
c2 <- "Pop"
valc2 <- "Au"
fact <- "year"
```

```{r,warning=FALSE,echo=FALSE,fig.show='hide'}
valc1 <- 1
maxdat <- max(centauree_data$age0[centauree_data$Size0Mars==valc1])
mindat <- min(centauree_data$age0[centauree_data$Size0Mars==valc1])
wrap_plots(
plot_flow(prediction = Flowpredict1, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict2, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict3, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict4, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict5, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat)
)

valc1 <- 5
maxdat <- max(centauree_data$age0[centauree_data$Size0Mars==valc1])
mindat <- min(centauree_data$age0[centauree_data$Size0Mars==valc1])
wrap_plots(
plot_flow(prediction = Flowpredict1, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict2, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict3, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict4, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict5, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat)
)

valc1 <- 15
maxdat <- max(centauree_data$age0[centauree_data$Size0Mars==valc1])
mindat <- min(centauree_data$age0[centauree_data$Size0Mars==valc1])
wrap_plots(
plot_flow(prediction = Flowpredict1, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict2, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict3, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict4, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict5, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat)
)
```

### En fixant l'année : voir l'effet population
```{r}
var <- "age0"
c1 <- "Size0Mars"
c2 <- "year"
valc2 <- 2000
fact <- "Pop"
```

```{r,warning=FALSE,echo=FALSE,fig.show='hide'}
valc1 <- 1
maxdat <- max(centauree_data$age0[centauree_data$Size0Mars==valc1])
mindat <- min(centauree_data$age0[centauree_data$Size0Mars==valc1])
wrap_plots(
plot_flow(prediction = Flowpredict1, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict2, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict3, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict4, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict5, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat)
)

valc1 <- 5
maxdat <- max(centauree_data$age0[centauree_data$Size0Mars==valc1])
mindat <- min(centauree_data$age0[centauree_data$Size0Mars==valc1])
wrap_plots(
plot_flow(prediction = Flowpredict1, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict2, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict3, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict4, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict5, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat)
)

valc1 <- 15
maxdat <- max(centauree_data$age0[centauree_data$Size0Mars==valc1])
mindat <- min(centauree_data$age0[centauree_data$Size0Mars==valc1])
wrap_plots(
plot_flow(prediction = Flowpredict1, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict2, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict3, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict4, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat),
plot_flow(prediction = Flowpredict5, var=var, c1=c1, valc1=valc1, c2=c2, valc2=valc2, fact=fact, maxdat = maxdat, mindat = mindat)
)
```