---
title: "Plantules size Models Fitted"
author: "Loïc Pages"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  word_document: default
  html_document:
    df_print: paged
---
  
# Introduction
  
```{r}
rm(list=ls())
library(knitr)
library(spaMM)
library(tidyverse)
library(splines)
library(patchwork)
library(SplinesUtils)

setwd("/media/loic/Commun/0Travail/Stage 2025 ISEM/Models")

centauree_data <- read.csv("donnesIPM_short.csv")
centauree_data_complet <- read.csv("donnesIPM.csv")


#Supprimer plantes dont l'age est inconnu
centauree_data <- centauree_data[!is.na(centauree_data$age0), ]
centauree_data$age1 <- ifelse(centauree_data$Stage1=="V",centauree_data$age0+1,NA)

#Forcer l'age maximal à 8
length(centauree_data$age0[centauree_data$age0 >= 8])
centauree_data$age0[centauree_data$age0 > 8] <- 8

spaMM.options(separation_max=70)
```


```{r}
annees <- 1995:2022
populations <- c("Po","Au","Pe","E1","E2","Cr")
taille_range <- seq(0.5, 25, by = 0.5) 
age_range <- 1:8

fake_data <- expand.grid(
  year = annees,
  Pop = populations,
  Size0Mars = taille_range,
  age0 = age_range
)

fake_data <- fake_data %>% 
  mutate(Nrw = row_number())
```

BIC
```{r}
extractBIC <- function(fit, n){
  extractAIC(fit)[[2]]+(log(n)-2)*DoF(fit)[[3]]
}
```

Test Splines -> poly
```{r}
survdata <- centauree_data[centauree_data$Flowering0!=1,]
survdata <- survdata[!is.na(survdata$SurvieMars),]

library(nlme)
library(SplinesUtils)
spline_model <- lme(SurvieMars ~ bs(age0, degree=3, knots=6.5)+bs(Size0Mars,df=5), data = survdata, random = list(
  year = pdSymm(~ Size0Mars), 
  Pop = pdSymm(~ age0)))

spl <- RegSplineAsPiecePoly(spline_model, "bs(Size0Mars, df = 5)")
spl2 <- RegSplineAsPiecePoly(spline_model, "bs(age0, degree = 3, knots = 6.5)")

spl$PiecePoly$coef
spl
```

# Taille des plantules

```{r}
plantule_data <- centauree_data[centauree_data$age0==1,]
```

```{r}
# Taille des plantules / année

plantule_data %>% 
  ggplot(aes(x = year, y = Size0Mars)) +
  geom_count(alpha=0.6) +
  labs(x = "Année",
       y = "Taille des plantules") +
  theme_minimal()

# Taille des plantules / population

plantule_data %>% 
  ggplot(aes(x = Pop, y = Size0Mars)) +
  geom_count(alpha=0.6) +
  labs(x = "Population",
       y = "Taille des plantules") +
  theme_minimal()
```



```{r}
Pltglm1 <- fitme(Size0Mars ~ 1 + (1|year) + (1|Pop) + (1|Pop:year), 
                 data=plantule_data,
                 family = Gamma(log))

Pltglm2 <- fitme(Size0Mars ~ 1 + (1|Pop) + (1|Pop:year), 
                 data=plantule_data,
                 family = Gamma(log))

Pltglm3 <- fitme(Size0Mars ~ 1 + (1|Pop:year), 
                 data=plantule_data,
                 family = Gamma(log))

Pltglm4 <- fitme(Size0Mars ~ 1 + (1|year) + (1|Pop:year), 
                 data=plantule_data,
                 family = Gamma(log))

Pltglm5 <- fitme(Size0Mars ~ 1 + (1|year) + (1|Pop), 
                 data=plantule_data,
                 family = Gamma(log))
```

```{r}
n <- length(plantule_data$Nrw)
extractAIC(Pltglm1) ; extractBIC(Pltglm1, n)
extractAIC(Pltglm2) ; extractBIC(Pltglm2, n)
extractAIC(Pltglm3) ; extractBIC(Pltglm3, n)
extractAIC(Pltglm4) ; extractBIC(Pltglm4, n)
extractAIC(Pltglm5) ; extractBIC(Pltglm5, n)
```

```{r}
summary(Pltglm1)
summary(Pltglm2)
summary(Pltglm3)
summary(Pltglm4)
summary(Pltglm5)
```

```{r,results='hide'}
Pltpredict1 <- predict(Pltglm1, newdata = fake_data)[,1]
Pltpredict2 <- predict(Pltglm2, newdata = fake_data)[,1]
Pltpredict3 <- predict(Pltglm3, newdata = fake_data)[,1]
Pltpredict4 <- predict(Pltglm4, newdata = fake_data)[,1]
Pltpredict5 <- predict(Pltglm5, newdata = fake_data)[,1]
```


```{r}
plot_plantule <- function(data = fake_data, prediction, var, fact) {
  data %>%
    mutate(plt_predi = prediction) %>%
    ggplot(aes(x = .data[[var]], y = plt_predi)) +
    geom_line(aes(color = as.factor(.data[[fact]]))) +
    labs(y="Taille des plantules")+
    theme_minimal()
}

plot_plantule1 <- function(data = fake_data, prediction, var, fact) {
  data %>%
    mutate(plt_predi = prediction) %>%
    ggplot(aes(x = .data[[var]], y = plt_predi)) +
    geom_point(aes(color = as.factor(.data[[fact]]))) +
    labs(y="Taille des plantules")+
    theme_minimal()
}

plot_plantule2 <- function(data = fake_data, prediction) {
  data %>%
    mutate(plt_predi = prediction) %>%
    ggplot(aes(x = plt_predi)) +
    geom_histogram() +
    labs(x="Taille des plantules")+
    theme_minimal()
}
```


## Taille des plantules en fonction de l'année

var <- "year"
fact <- "Pop"

```{r,warning=FALSE,echo=FALSE}
var <- "year"
fact <- "Pop"

wrap_plots(
  plot_plantule(prediction = Pltpredict1, var=var, fact=fact),
  plot_plantule(prediction = Pltpredict2, var=var, fact=fact),
  plot_plantule(prediction = Pltpredict3, var=var, fact=fact),
  plot_plantule(prediction = Pltpredict4, var=var, fact=fact),
  plot_plantule(prediction = Pltpredict5, var=var, fact=fact)
)
```

## Taille des plantules en fonction de la population

var <- "Pop"
fact <- "year"

```{r,warning=FALSE,echo=FALSE}
var <- "Pop"
fact <- "year"

wrap_plots(
  plot_plantule1(prediction = Pltpredict1, var=var, fact=fact),
  plot_plantule1(prediction = Pltpredict2, var=var, fact=fact),
  plot_plantule1(prediction = Pltpredict3, var=var, fact=fact),
  plot_plantule1(prediction = Pltpredict4, var=var, fact=fact),
  plot_plantule1(prediction = Pltpredict5, var=var, fact=fact)
)
```
## Densité de taille de plantule
```{r,warning=FALSE,echo=FALSE}
wrap_plots(
  plot_plantule2(prediction = Pltpredict1),
  plot_plantule2(prediction = Pltpredict2),
  plot_plantule2(prediction = Pltpredict3),
  plot_plantule2(prediction = Pltpredict4),
  plot_plantule2(prediction = Pltpredict5)
)
```

