---
title: "Establishment Models Fitted"
author: "Loïc Pages"
date: "28/02/2025"
output:
  pdf_document: default
  word_document: default
  html_document:
    df_print: paged
---

  
# Introduction
  
```{r}
rm(list=ls())
library(knitr)
library(spaMM)
library(tidyverse)
library(splines)
library(foreach)
library(doParallel)
library(patchwork)

setwd("/media/loic/Commun/0Travail/2025 IPM Centauree ISEM/2025 Stage ISEM/Code")

IPM_data <- read.csv("newdata.csv")

centauree_data <- IPM_data[!is.na(IPM_data$Size0Mars) & !is.na(IPM_data$Age),]
centauree_data$Age[centauree_data$Age > 8] <- 8

spaMM.options(separation_max=70)
```


```{r}
annees <- 1995:2022
populations <- c("Po","Au","Pe","E1","E2","Cr")
taille_range <- seq(0.5, 25, by = 0.5) 
age_range <- 1:8

fake_data <- expand.grid(
  year = annees,
  Pop = populations
)

fake_data <- fake_data %>% 
  mutate(Nrw = row_number())
```

BIC
```{r}
extractBIC <- function(fit, n){
  extractAIC(fit)[[2]]+(log(n)-2)*DoF(fit)[[3]]
}
```


# Establishment rate 

Remplir les données manquantes de nombres de capitules avec des prédictions.
```{r}
Cptlglm1 <- fitme(log(Capitule) ~ 1 + Size0Mars+ (Age|year),
                  data=cptldata)
# NbrCptl = exp(2.31070+0.06846*Size0Mars)
cptl_data_predi <- cptldata %>%
  mutate(Capitule = ifelse(is.na(Capitule), exp(2.31070+0.06846*Size0Mars), Capitule))

plt <- IPM_data %>% 
  filter(Age==1) %>% 
  group_by(Quadrat,year,Pop) %>% 
  summarize(NombrePlantules = sum(Age))

cptl <- cptl_data_predi %>% 
  group_by(Quadrat,year,Pop) %>% 
  summarize(Capitule = sum(Capitule))

#Calcul avec la formule d'origine utilisant les données brutes
Estb <- inner_join(plt,cptl, by=join_by(Quadrat,year,Pop))

Estb <- Estb %>% mutate(EstbRate=rep(NA)) %>%
  arrange(Quadrat)

for (i in 2:length(Estb$Quadrat)){
  if (Estb$Quadrat[i]!=Estb$Quadrat[i-1]){next}
  if (Estb$year[i]!=Estb$year[i-1]+1){next}
  Estb$EstbRate[i] <- Estb$NombrePlantules[i]/Estb$Capitule[i-1]
}
Estb <- Estb %>%
  group_by(Pop,year) %>%
  mutate(EstbPop = mean(EstbRate,na.rm=TRUE))

Estbglm1 <- fitme(EstbRate ~ 1 , data=Estb)

Estb <- left_join(plt, cptl, by = join_by(Quadrat, year, Pop))


Estbglm2 <- fitme(NombrePlantules ~ 1 + offset(log(Capitule)) + (1|Pop:year),
                  data = Estb,
                  family = Poisson(log))

Estbglm3 <- fitmv(submodels=list(list(as.integer(Capitule) ~ 1+(0+mv(1,2)|Pop:year),family=poisson()),
                                 list(NombrePlantules ~ 1+(0+mv(1,2)|Pop:year),family=poisson())), 
                  data=Estbglm2$data)
```

```{r}
foo <- predict(Estbglm3,newdata = fake_data)
mv <- attr(foo,"mv")
fake_data$predratio <- mv[[2]]/mv[[1]]
fake_data$predPlantules <- mv[[2]]
fake_data$predCapitules <- mv[[1]]

ggplot(data=fake_data,aes(x = year, y = predratio)) +
  geom_line(aes(color = as.factor(Pop))) +
  labs(y="Establishment rate")+
  theme_minimal()+
  scale_color_viridis_d(option = "plasma")

ggplot(data=fake_data, aes(x = year, y = predPlantules)) +
  geom_line(aes(color = as.factor(Pop))) +
  labs(y="Nombre prédi de plantules")+
  theme_minimal()+
  scale_color_viridis_d(option = "plasma")


```


```{r}
foo <- predict(Estbglm3)
mv <- attr(foo,"mv")
dat <- Estbglm3$data
dat$predratio <- mv[[2]]/mv[[1]]
dat$predPlantules <- mv[[2]]
 
dat %>% group_by(Pop,year) %>% 
  summarise(predratio = mean(predratio)) %>% 
ggplot(aes(x = year, y = predratio)) +
  geom_line(aes(color = as.factor(Pop))) +
  labs(y="Establishment rate")+
  theme_minimal()+
  scale_color_viridis_d(option = "plasma")

ggplot(data=dat, aes(x = Capitule, y = predPlantules)) +
  geom_line(aes(color = as.factor(Pop))) +
  labs(y="Nombre prédi de plantules")+
  theme_minimal()+
  scale_color_viridis_d(option = "plasma")


foo <- predict(Estbglm3bis)
mv <- attr(foo,"mv")
dat <- Estbglm3bis$data
dat$predratio <- mv[[2]]/mv[[1]]
dat$predPlantules <- mv[[2]]
 
dat %>% group_by(Pop,year) %>% 
  summarise(predratio = mean(predratio)) %>% 
ggplot(aes(x = year, y = predratio)) +
  geom_line(aes(color = as.factor(Pop))) +
  labs(y="Establishment rate")+
  theme_minimal()+
  scale_color_viridis_d(option = "plasma")

ggplot(data=dat, aes(x = Capitule, y = predPlantules)) +
  geom_line(aes(color = as.factor(Pop))) +
  labs(y="Nombre prédi de plantules")+
  theme_minimal()+
  scale_color_viridis_d(option = "plasma")
```


```{r}
Estbglm1 <- fitme(EstbRate ~ 1 + (1|Pop:year), data=Estb)
Estbglm2 <- fitme(EstbRate ~ 1 +(1|year), data=Estb)
Estbglm3 <- fitme(EstbRate ~ 1 + (1|year) + (1|Pop:year), data=Estb)
Estbglm4 <- fitme(EstbRate ~ 1, data=Estb)
Estbglm5 <- fitme(EstbRate ~ 1 + (1|Pop) + (1|Pop:year), data=Estb)

Estbglm1
Estbglm2
Estbglm3
Estbglm4
Estbglm5
```

```{r}
n <- length(Estb$Quadrat)
extractAIC(Estbglm1) 
extractAIC(Estbglm2) 
extractAIC(Estbglm3) 
extractAIC(Estbglm4) 
extractAIC(Estbglm5) 
```

```{r,results='hide'}
Estbpredict1 <- predict(Estbglm1, newdata = fake_data)[,1]
Estbpredict2 <- predict(Estbglm2, newdata = fake_data)[,1]
Estbpredict3 <- predict(Estbglm3, newdata = fake_data)[,1]
Estbpredict4 <- predict(Estbglm4, newdata = fake_data)[,1]
Estbpredict5 <- predict(Estbglm5, newdata = fake_data)[,1]
```

```{r}
plot_estb <- function(data = fake_data, prediction, var, fact) {
  data %>%
    mutate(plt_predi = prediction) %>%
    ggplot(aes(x = .data[[var]], y = plt_predi)) +
    geom_line(aes(color = as.factor(.data[[fact]]))) +
    labs(y="Establishment rate")+
    theme_minimal()
}

plot_estb2 <- function(data = fake_data, prediction, var, fact) {
  data %>%
    mutate(plt_predi = prediction) %>%
    ggplot(aes(x = .data[[var]], y = plt_predi)) +
    geom_point(aes(color = as.factor(.data[[fact]]))) +
    labs(y="Establishment rate")+
    theme_minimal()
}
```

```{r}
    ggplot(data=dat, aes(x = year, y = predratio)) +
    geom_line(aes(color = as.factor(Pop))) +
    labs(y="Establishment rate")+
    theme_minimal()
```

## Establishment rate en fonction de l'année

var <- "year";
fact <- "Pop"
```{r,warning=FALSE,echo=FALSE,fig.show='hide'}
var <- "year"
fact <- "Pop"

wrap_plots(
  plot_estb(prediction = Estbpredict1, var=var, fact=fact),
  plot_estb(prediction = Estbpredict2, var=var, fact=fact),
  plot_estb(prediction = Estbpredict3, var=var, fact=fact),
  plot_estb(prediction = Estbpredict4, var=var, fact=fact),
  plot_estb(prediction = Estbpredict5, var=var, fact=fact)
)
```

## Establishment rate en fonction de la population
var <- "Pop";
fact <- "year"
```{r,warning=FALSE,echo=FALSE,fig.show='hide'}
var <- "Pop"
fact <- "year"

wrap_plots(
  plot_estb2(prediction = Estbpredict1, var=var, fact=fact),
  plot_estb2(prediction = Estbpredict2, var=var, fact=fact),
  plot_estb2(prediction = Estbpredict3, var=var, fact=fact),
  plot_estb2(prediction = Estbpredict4, var=var, fact=fact),
  plot_estb2(prediction = Estbpredict5, var=var, fact=fact)
)
```

