---
title: "Appendix B: R code for the evolutionary IPM"
author: "Adèle Erlichman & Ophélie Ronce (modified by Loïc Pages)"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  word_document: default
  html_document:
  df_print: paged
---

```{r}
load("/media/loic/Commun/0Travail/2025 IPM Centauree ISEM/2025 Stage ISEM/Code/IPM/ModelsAIC.RData")
annees <- 1995:2022
populations <- c("Po","Au","Pe","E1","E2","Cr")
```

Survival probability  

```{r}
s.x <- function(a, x) { 
  fake_data <- expand.grid(
    year = annees,
    Pop = populations,
    Size0Mars = x,
    Age = a)
  if(a==1){
    predi <- predict(Survglm11, fake_data, allow.new.levels = T)
    u <- aggregate(predi, list(fake_data$Size0Mars), mean)
  }
  if(a!=1){
    predi <- predict(Survglm12, fake_data, allow.new.levels = T)
    u <- aggregate(predi, list(fake_data$Size0Mars), mean)
  }
  return(u$V1)
}  
```

Flowering probability  
```{r}
f.x <- function(a, x) { 
  fake_data <- expand.grid(
    year = annees,
    Pop = populations,
    Size0Mars = unique(x),
    Age = a)
  predi <- plogis(predict(Flowglm1, newdata = fake_data, allow.new.levels = T, type = "link")) 
  u <- aggregate(predi, list(fake_data$Size0Mars), mean)
return(u$V1)
  }  
```

Number of capitula   
```{r}
c.x <- function(a, x) { 
  fake_data <- expand.grid(
    year = annees,
    Pop = populations,
    Size0Mars = x,
    Age = a) 
  predi <- exp(predict(Cptlglm1, fake_data))
  meanpredi <- aggregate(predi, list(fake_data$Size0Mars), mean)
  # meanpredi$V1[meanpredi$Group.1<5] <- 0 #Nbr of capitulas=0 if size<5 cm
  value <- ifelse(meanpredi$V1>=0,meanpredi$V1,0) #Avoid nbr of capitulas==0
return(value) } 
```

Seedling size distribution 
```{r}
ssd.y <- function(ysup, yinf) {
  yinf <- ifelse(yinf==0.5,-Inf,yinf)
  fake_data <- expand.grid(
  year = annees,
  Pop = populations)
  
  predi <- predict(Pltglm1, newdata = fake_data)[, 1]
  meanpredi <- mean(predi)
  shape <- 1 / Pltglm1$phi
  scale <- meanpredi * Pltglm1$phi
  cdf.sup <- pgamma(ysup, shape = shape, scale = scale)
  cdf.inf <- pgamma(yinf, shape = shape, scale = scale)
  return(cdf.sup - cdf.inf)}  
```

Establishment rate  
```{r}
Estbli <- function(Pop=populations, year=annees){
  fake_data <- expand.grid(
  year = year,
  Pop = Pop,
  Capitule = 1:200)
  plt <- predict(Estbglm2, newdata = fake_data)[,1]
  mu <- mean(plt/fake_data$Capitule)
  return(mu)
}
```

Evolution of the growth function  
```{r}
sigmaG <- function(a,x) {
  fake_data <- expand.grid(
    year = annees,
    Pop = populations,
    Size0Mars = unique(x),
    Age = a)
  resvar <- predict(Growthglm2$resid_fit, newdata = fake_data, allow.new.levels = T)
  value <- aggregate(resvar[,1], list(fake_data$Size0Mars), mean)$x
   return(value)
  } 

 G.yxz <- function(ysup,yinf,x,a,z,sigmaz){  
  sizepow <- 0.4343354
  yinfpow <- yinf**sizepow
  ysuppow <- ysup**sizepow
  yinfpow[1] <- -Inf
  ysuppow[length(ysuppow)] <- Inf
  
  fake_data <- expand.grid(
  year = annees,
  Pop = populations,
  Size0Mars = unique(x),
  Age = a)
  predi <- predict(Growthglm2, fake_data, allow.new.levels = T) #Predicted size^pow at t+1 for all combinations of pop, year, age and size at t
  meanpredi <- aggregate(predi, list(fake_data$Size0Mars), mean) #Make the prediction data more usable, and take the mean over the populations and years for each size/age class.
  
  resvar <- predict(Growthglm2$resid_fit, newdata = fake_data, allow.new.levels = T)
  meanresvar <- aggregate(resvar[,1], list(fake_data$Size0Mars), mean)$x
  
  cdf.supG <- mapply(pnorm, mean = meanpredi$V1, sd = sqrt(meanresvar), MoreArgs = list(q=ysuppow))
  cdf.infG <- mapply(pnorm, mean = meanpredi$V1, sd = sqrt(meanresvar), MoreArgs = list(q=yinfpow))
  
  cdf.supZ <- mapply(pnorm, mean = 0, sd = sigmaz)
  cdf.infZ <- mapply(pnorm, mean = 0, sd = sigmaz)
  
  cdf.supGZ <- mapply(pnorm, mean = meanpredi$V1, sd = sqrt(meanresvar)+sigmaz, MoreArgs = list(q=ysuppow))
  cdf.infGZ <- mapply(pnorm, mean = meanpredi$V1, sd = sqrt(meanresvar)+sigmaz, MoreArgs = list(q=yinfpow))
  
  return(cdf.infGZ + cdf.supGZ - cdf.infZ*cdf.infG*(cdf.supZ-cdf.infZ+cdf.supG-cdf.infG))
}
```

 Functions that describe life history  
```{r}
# fecundity function  
fmean <- function(a, ysup,yinf, x) {
  value = Estbli() * f.x(a, x) * c.x(a, x) * ssd.y(ysup,yinf) 
  valueFec = ifelse(value >= 0, value , 0) 
return(valueFec) 
  }

# survival growth function (mean transition rate from j to i) 
tmean <- function(a, ysup, yinf, x, z, sigmaz) { 
  value = s.x(a, x) * (1 - f.x(a, x)) * G.yxz(a, x, ysup, yinf, z, sigmaz) 
return(value) 
  }  


theta.xy <- function(a, x, y){
  value <- 0
  return(value)
}

# derivative of the log transition rate from j to i # with respect to the mean phenotypic value (z) at j 
dlntmean <- function(a, y, x, z, sigmaz) { 
  value = (theta.xy(a, x, y) - z) / (sigmaG(x)^2 + sigmaz^2)
return(value)
}
```


Transition matrix generator  
```{r}
# Builds the transition matrix using the z vector 
TransitionMatrixGenerator <- function(a, zvec, sigmazvec, n) {
  minsize <-  0.5
  maxsize <-  25
  maxsize1 <- 15
  h <-  (maxsize - minsize) / n
  h1 <-  (maxsize1 - minsize) / n
  b <- minsize + c(0:n) * h

  #sizes for an individual of age a
  #midpoint
  ymid.a = 0.5 * (b[1:n] + b[2:(n + 1)])
  #intervals
  yI.a <- matrix(nrow = n, ncol = 2)
  for (i in 1:n){
    yI.a[i,1] <- b[i]
    yI.a[i,2] <- b[i+1]
  }
  
  b1 = minsize + c(0:n) * h1
  #sizes for an individual of age 1
  #midpoint
  ymid.1 = 0.5 * (b1[1:n] + b1[2:(n + 1)])
  #intervals
  yI.1 <- matrix(nrow = n, ncol = 2)
  for (i in 1:n){
    yI.1[i,1] <- b1[i]
    yI.1[i,2] <- b1[i+1]
  }
  
  if(a==1){h <- h1
    ymid.a <- ymid.1
  }

  # Define zvec and sigmaz for this age class a 
  zvec_a = zvec[(a*n-(n-1)):(a*n)] 
  sigmazvec_a = sigmazvec[(a*n-(n-1)):(a*n)]  
  
  # Survival - Growth matrix 
  # Define empty matrix  
  SG = matrix(c(NA), ncol = n, nrow = n) 
  for (i in c(1:n)) { 
    for (j in c(1:n)) { 
      SG[i, j] <- tmean(a, yI.a[j,2], yI.a[j,1], ymid.a[i], zvec_a[j], sigmazvec_a[j]) } }  
  
  # Fecundity matrix  
  F = matrix(c(NA), ncol = n, nrow = n) 
  for (i in c(1:n)) { 
    for (j in c(1:n)) { 
      F[i, j] <- fmean(a, yI.1[j,2], yI.1[j,1], ymid.a[i]) } }  
  
  # Full matrix  
  kernel = SG + F  
  
  # dlntij  
  dlnSG = matrix(c(NA), ncol = n, nrow = n) 
    for (i in c(1:n)) { 
      for (j in c(1:n)) { 
        dlnSG[i, j] <- h.a1 * dlntmean(a, y.a1[i], y.a[j], zvec_a[j], sigmazvec_a[j]) } }  
    
  return(list(  K = kernel, # full kernel (TM+FM) 
                TM = SG, # transition matrix
                FM = F, # Fecundity matrix 
                dlnTM = dlnSG # derivative of the log of TM 
                )) }
```


Full matrix generator 
```{r}
# Builds the age + size structured Kernel  
MatrixGenerator = function(age.max, zvec, sigmazvec, MatrixDim, min.size, max.size) { 
  TM.k = matrix(data = NA, nrow = MatrixDim, ncol = MatrixDim) 
  FM.k = matrix(data = NA, nrow = MatrixDim, ncol = MatrixDim) 
  K.k = matrix(data = NA, nrow = MatrixDim, ncol = MatrixDim) 
  Kernals = array(data = 0, dim = c(age.max, 3, MatrixDim, MatrixDim)) 
  superMatrix = array(0, dim = c((age.max * MatrixDim), (age.max * MatrixDim))) 
  for (a in (1:(age.max - 1))) { 
    Kls = TransitionMatrixGenerator(a, zvec, sigmazvec, MatrixDim, min.size, max.size) 
    Kernals[a, 1, , ] = Kls$K 
    Kernals[a, 2, , ] = Kls$TM 
    Kernals[a, 3, , ] = Kls$FM 
    debut = (a - 1) * MatrixDim + 1 
    fin = debut + (MatrixDim - 1) 
    superMatrix[1:MatrixDim, (debut:fin)] = Kls$FM 
    superMatrix[((fin + 1):(fin + MatrixDim)), (debut:fin)] = Kls$TM }  
  Kls = TransitionMatrixGenerator(age.max, zvec, sigmazvec, MatrixDim, min.size, max.size) 
  Kernals[age.max, 1, , ] = Kls$K 
  Kernals[age.max, 2, , ] = Kls$TM 
  Kernals[age.max, 3, , ] = Kls$FM 
  debut = (age.max - 1) * MatrixDim + 1 
  fin = debut + (MatrixDim - 1) 
  superMatrix[1:MatrixDim, (debut:fin)] = Kls$FM 
  superMatrix[(debut:fin), (debut:fin)] = Kls$TM  
return(superMatrix) }  
```



Full dln matrix generator  
```{r}
# Builds the dlnTT matrix  
dlnMatrixGenerator = function(age.max, zvec, sigmazvec, MatrixDim, min.size, max.size) { 
  TM.k = matrix(data = NA, nrow = MatrixDim, ncol = MatrixDim) 
  FM.k = matrix(data = NA, nrow = MatrixDim, ncol = MatrixDim) 
  K.k = matrix(data = NA,nrow = MatrixDim, ncol = MatrixDim) 
  Kernals = array(data = 0, dim = c(age.max, 3, MatrixDim, MatrixDim)) 
  superMatrix = array(0, dim = c((age.max * MatrixDim), (age.max * MatrixDim))) 
  
  for (a in (1:(age.max - 1))) { 
    Kls = TransitionMatrixGenerator(a, zvec, sigmazvec, MatrixDim, min.size, max.size) 
    debut = (a - 1) * MatrixDim + 1 
    fin = debut + (MatrixDim - 1) 
    superMatrix[1:MatrixDim, (debut:fin)] = 0 
    superMatrix[((fin + 1):(fin + MatrixDim)), (debut:fin)] = Kls$dlnTM }  
  
  Kls = TransitionMatrixGenerator(age.max, zvec, sigmazvec, MatrixDim, min.size, max.size) 
  Kernals[age.max, 1, , ] = Kls$K 
  Kernals[age.max, 2, , ] = Kls$TM 
  Kernals[age.max, 3, , ] = Kls$FM 
  debut = (age.max - 1) * MatrixDim + 1 
  fin = debut + (MatrixDim - 1) 
  superMatrix[1:MatrixDim, (debut:fin)] = 0 
  superMatrix[(debut:fin), (debut:fin)] = Kls$dlnTM  
  return(superMatrix) }
```

  General recursion 
```{r}
  # The general recursion defines the phenotypic and breeding values
# based on the transition matrices  
GeneralRecursion <- function(g0, z0, N0, sigmag, sigmaz, age.max, MatrixDim, min.size, max.size) { 
  # define empty vectors for phenotype and breeding value 
  zt1 = rep(NA, length(N0)) 
  gt1 = rep(NA, length(N0)) 
  # full kernel  
  K = MatrixGenerator(age.max, z0, sigmaz, MatrixDim, min.size, max.size)  
  # compute number of individuals at t+1 
  Nt1 = K %*% N0  
  # fecundity matrix 
  FF = K 
  FF[(MatrixDim + 1):(MatrixDim * age.max),] = 0  
  # transition matrix 
  TT = K 
  TT[1:MatrixDim,] = 0 
# derivative of the log transition matrix  
  dlnTT = dlnMatrixGenerator(age.max, z0, sigmaz, MatrixDim, min.size, max.size)  
  # recursion for g values at t  
  for (i in 1:(MatrixDim * age.max)) { 
    if (Nt1[i] == 0) { gt1[i] = 0 }
    else {  
      j = 1:(MatrixDim * age.max) 
      gt1[i] = sum((N0[j]*TT[i, j]/Nt1[i]) * (g0[j] + sigmag[j]^2 *dlnTT[i, j]) + ((N0[j]*FF[i, j]/Nt1[i])*(g0[j]))) } }  
  # recursion for z values at t  
  for (i in 1:(MatrixDim * age.max)) { 
    if (Nt1[i] == 0) { zt1[i] = 0 } 
    else {  
      j = 1:(MatrixDim * age.max) 
      zt1[i] = sum((N0[j]*TT[i, j]/Nt1[i]) * (z0[j] + sigmaz[j]^2 *dlnTT[i, j]) + ((N0[j]*FF[i, j]/Nt1[i])*(g0[j]))) } }  
  return(list(gt = gt1, zt = zt1)) }
```
  
  Running recursion 
```{r}
RunRecursion <- function(g0, z0, N0, sigmag, sigmaz, age.max, MatrixDim, min.size, max.size, nyears) { 
  # Define empty lists 
  zt = list() 
  gt = list() 
  Nt = list() 
  TT = list()  
  # Initialize for t=0 
  zt[[1]] <- z0 
  gt[[1]] <- g0 
  Nt[[1]] <- N0  
  # Recursion  
  for (t in 1:nyears) { 
    TT[[t]] = MatrixGenerator(age.max, zt[[t]], sigmaz, MatrixDim, min.size, max.size) 
    zt[[t + 1]] = GeneralRecursion(gt[[t]], zt[[t]], Nt[[t]], sigmag, sigmaz, age.max,MatrixDim, min.size, max.size)$zt 
    gt[[t + 1]] = GeneralRecursion(gt[[t]], zt[[t]], Nt[[t]], sigmag, sigmaz, age.max, MatrixDim, min.size, max.size)$gt 
    Nt[[t + 1]] = TT[[t]] %*% Nt[[t]] 
    print(t) }  
  
  # Data wrangling for nice outputs (number of individuals in each class) 
  TabNt = plyr::ldply(Nt, rbind) 
  year = rep(0:nyears, each = MatrixDim * age.max) 
  age = rep(rep(1:age.max, each = MatrixDim), nyears + 1) 
  size.age = rep(rep(1:MatrixDim), age.max*(nyears+1)) 
  size = vector() 
  compteur=1 
  for(a in 1:age.max){ 
    b = min.size[a] + c(0:MatrixDim) * (max.size[a] - min.size[a]) / MatrixDim
    midpoints = 0.5 * (b[1:MatrixDim] + b[2:(MatrixDim + 1)]) 
    size[compteur:(compteur+(MatrixDim-1))] = midpoints 
    compteur=compteur+MatrixDim }  
  sizevec = rep(size, nyears + 1) 
  zini = rep(z0[1], each = MatrixDim * age.max) 
  gini = rep(g0[1], each = MatrixDim * age.max) 
  sigmazini = rep(sigmaz[1], each = MatrixDim * age.max) 
  sigmagini = rep(sigmag[1], each = MatrixDim * age.max)  
  NTT <- data.table(year, age, size.age, sizevec, zini, gini, sigmazini, sigmagini, TabNt) 
  colnames(NTT) <- c("year", "age", "size.age", "size", "zini", "gini", "sigmazini", "sigmagini", "Nind")  
  
  # Data wrangling for nice outputs (breeding values) 
  GT = plyr::ldply(gt, rbind) 
  year = rep(0:nyears)
  GT <- data.table(year, GT) 
  GT = data.table::melt(GT, id.vars = "year") 
  GT$size = rep(rep(1:MatrixDim, each = nyears + 1), age.max) 
  GT$age = rep(1:age.max, each = (nyears + 1) * MatrixDim) 
  colnames(GT) <- c("year", "age.size", "gt", "size", "age")  
  # Data wrangling for nice outputs (phenotypic values) 
  ZT = plyr::ldply(zt, rbind)
  year = rep(0:nyears) 
  ZT <- data.table(year, ZT) 
ZT = data.table::melt(ZT, id.vars = "year") 
ZT$size = rep(rep(1:MatrixDim, each = nyears + 1), age.max) 
ZT$age = rep(1:age.max, each = (nyears + 1) * MatrixDim) 
colnames(ZT) <- c("year", "age.size", "zt", "size", "age")  
return(list( NT = NTT, gT = GT, zT = ZT, TM = TT )) }
```
  
Simple run exemple  
```{r}
 # Define matrix dimension 
MatrixDim = 50  
# Define number of years for simulation 
nyears = 50  
# Define oldest age class 
age.max = 8  
# Define max size in each age class  
max.size = c(15.5, 20.5, 24.5, 25.5, 20.5, 25.5, 20.5, 25.5)
# Define min size in each age class  
min.size = c(0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1, 0.5)  
# To define the distribution of seedlings in the first cohort 
boundaries = min.size[1] + c(0:MatrixDim) * (max.size[1] - min.size[1]) / MatrixDim 
midpoints = 0.5 * (boundaries[1:MatrixDim] + boundaries[2:(MatrixDim + 1)]) 
# Consider 500 seedlings  
N0 <- matrix(c(500*ssd.y(midpoints), rep(0, (MatrixDim * age.max)-MatrixDim)), ncol = 1) 
# Initial phenotypic values: 0 in each class  
z0 = matrix(rep(0, MatrixDim * age.max), nrow = 1)
# Initial breeding values: 0 in each class  
g0 = matrix(rep(0, MatrixDim * age.max), nrow = 1)  
# Define input of variance 
z=2 
sigmaz = matrix(rep(z, MatrixDim * age.max), ncol = 1) 
# consider heritability is 0.5  
sigmag = matrix(rep(sqrt(0.5) * z, MatrixDim * age.max), ncol = 1)  


# Run  
output = RunRecursion(g0, z0, N0, sigmag, sigmaz, age.max, MatrixDim, min.size, max.size, nyears)
```
    
   